"""Reproducible expanded research. Never changes the production recommendation engine."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import time
import warnings

for variable in ["OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"]:
    os.environ.setdefault(variable, "1")

import numpy as np
import scipy
import sklearn

from evaluation import diagnose_draws, evaluate_models
from features import BASE_RATE, build_features, encode_draws, top_six
from models import adaptive_models, learned_models, statistical_models
from prospective import advance_shadow_records, digest, history_digest, summarize_prospective

ROOT = Path(__file__).resolve().parents[2]
RESEARCH_DIR = Path(__file__).resolve().parent


def main():
    warnings.simplefilter("error", RuntimeWarning)
    parser = argparse.ArgumentParser()
    parser.add_argument("--workers", type=int, default=3)
    args = parser.parse_args()
    started = time.monotonic()
    policy = json.loads((RESEARCH_DIR / "protocol.json").read_text())
    raw = json.loads((ROOT / "data/lotto-data.json").read_text())
    draws, outcomes = encode_draws(raw["draws"])
    features = build_features(outcomes)
    tie_breaks = np.random.default_rng(policy["randomSeed"]).random((len(outcomes) + 1, 45))
    print(f"Research through draw {draws[-1]['draw']}; protocol {policy['version']}", flush=True)
    scores = statistical_models(outcomes, features, policy)
    print(f"Computed {len(scores)} statistical models", flush=True)
    scores.update(learned_models(outcomes, features, policy, args.workers))
    adaptive, choices = adaptive_models(scores, outcomes, tie_breaks, policy)
    scores.update(adaptive)
    predictions = {name: top_six(score, tie_breaks) for name, score in sorted(scores.items())}
    baseline = json.loads(subprocess.check_output(["node", str(RESEARCH_DIR / "current-engine.mjs")], text=True))
    predictions["current"] = np.vstack([np.arange(1, 7), baseline])
    scores["current"] = np.full((len(outcomes) + 1, 45), BASE_RATE)
    report = evaluate_models(predictions, scores, outcomes, policy)
    report["diagnostics"] = diagnose_draws(outcomes, policy)
    source_files = sorted(RESEARCH_DIR.glob("*.py")) + sorted(RESEARCH_DIR.glob("*.mjs"))
    source_files += [RESEARCH_DIR / "requirements.txt", RESEARCH_DIR / "protocol.json"]
    source_files += [ROOT / "src/core" / name for name in ["recommendation-engine.js", "number-utils.js", "random.js"]]
    code_hash = hashlib.sha256(b"".join(str(path.relative_to(ROOT)).encode() + path.read_bytes() for path in source_files)).hexdigest()
    ledger_path = ROOT / "data/research-shadow-records.json"
    existing = json.loads(ledger_path.read_text())["records"] if ledger_path.exists() else []
    records = advance_shadow_records(existing, draws, predictions, policy, code_hash)
    report.update({"protocol": policy, "protocolHash": digest(policy), "codeHash": code_hash,
        "latestDraw": draws[-1]["draw"], "historyDigest": history_digest(draws),
        "versions": {"numpy": np.__version__, "scipy": scipy.__version__, "sklearn": sklearn.__version__},
        "prospective": summarize_prospective(records, policy), "productionEngineChanged": False,
        "adaptiveNextChoices": {name: selections[-1] for name, selections in choices.items()}})
    artifact = json.dumps(report, indent=2, ensure_ascii=False, allow_nan=False) + "\n"
    (ROOT / "data/research-analysis.json").write_text(artifact)
    (ROOT / "data/research-analysis.js").write_text("// Generated by scripts/research/run.py\nexport const RESEARCH_ANALYSIS = " + artifact.strip() + ";\n")
    ledger_path.write_text(json.dumps({"protocolHash": digest(policy), "records": records}, indent=2, allow_nan=False) + "\n")
    for row in sorted(report["models"], key=lambda row: -row["confirmation"]["meanHits"]):
        print(f"{row['id']:30s} development={row['development']['meanHits']:.3f} confirmation={row['confirmation']['meanHits']:.3f} "
            f"zero={row['confirmation']['zeroRate']:.3f} p_adj={row['confirmation']['adjustedPValue']:.4f}")
    print("Development-selected:", report["developmentSelectedModel"])
    print("Eligible for review:", report["eligibleModelIds"])
    print("Diagnostics:", json.dumps(report["diagnostics"]))
    print(f"Saved {len(predictions)} pre-draw forecasts for {records[-1]['targetDraw']}; elapsed {time.monotonic() - started:.1f}s", flush=True)


if __name__ == "__main__":
    main()
